version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.26
    cap_add:
        - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password --max_connections=30 --max_allowed_packet=32M --expire_logs_days=3 --max_binlog_size=100M --innodb_buffer_pool_size=1G --innodb_log_file_size=200M --innodb_buffer_pool_instances=2
    ports:
      - 3406:3306
    environment:
      MYSQL_DATABASE: build
      MYSQL_USER: build
      MYSQL_PASSWORD: build
      MYSQL_ROOT_PASSWORD: build
    restart: always
    volumes:
      - db_django:/var/lib/mysql
volumes:
  build:
  db_django: